import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import React from 'react'
import ReactPlayer from 'react-player'
import ReactMarkdown from 'react-markdown'

// import ModalVideo from 'react-modal-video'

export async function getServerSideProps({ query }) {
    var user = query.user
    try {
        const res = await fetch("https://www.reddit.com/u/" + user + ".json");
        const posts = await res.json();
        return {
            props: {
                data: posts.data.children,
                uname: user,
            }, // will be passed to the page component as props
        };
    } catch (error) {
        const err = error;
        return {
            props: {
                posts: [],
                err: JSON.stringify(err),
            }, // will be passed to the page component as props
        };
    }
}

function betterwrap(str, width, brk, cut) {
    // Cut is only for compatiblity with old wrap
    let splited = str.split(" ")
    let finalstring = ""
    let count = 0
    for (var part in splited) {
        count = count + 1
        finalstring = finalstring + splited[part] + " "
        if (count == width) {
            finalstring = finalstring + brk
            count = 0
        }   
    }

    return finalstring
}

export default function Home(props) {
    var user = props['data']
    // console.log(user);
    return (
        <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/blocks.css/dist/blocks.min.css" />
      </Head>
        <main className={styles.main}>
      <div><h1 className={styles.title}>Deddit - {props['uname']}</h1></div>
        <div className={styles.grid}>
        
          {
            Object.entries(user).map(([key, post]) => {
              //console.log(post)
              let type = post.data.post_hint;
              // console.log(type)
              // console.log(Object.keys(post.data))

              if (type == "image") {
                return (
                  <div className="wrapper inline fixed block" key={key}>
                    <div>
                      <h2 className={"block fixed " + styles.textcenter}>{post.data.title}</h2>
                      <a href={post.data.url}><img className={styles.imagecenter} src={post.data.url} height="300" /></a>
                    </div>
                  </div>
                )
              }
              else if (type == "link") {
                return (
                  <div className="wrapper fixed block" key={key}>
                    <div>
                      <h2 className={"block fixed " + styles.textcenter}>{post.data.title}</h2>
                      <a className={styles.link} href={post.data.url}><h3>{post.data.title}</h3></a>
                    </div>
                  </div>
                )
              }
              else if (type == "hosted:video") {
                let src = post.data.media.reddit_video.fallback_url
                // console.log(post.data)
                // console.log(src)
                return (
                  <div className="wrapper fixed block" key={key}>
                    <div>
                      <h2 className={"block fixed " + styles.textcenter}>{post.data.title}</h2>
                      <p>{type}</p>
                      <ReactPlayer url={src} controls='true' />
                    </div>
                  </div>
                )
              }
              else if (type == "rich:video") {
                let html = post.data.media.oembed.html
                // console.log(post.data)
                // console.log(src)
                // let src = ""
                return (
                  <div className="wrapper fixed block" key={key}>
                    <div>
                      <h2 className={"block fixed " + styles.textcenter}>{post.data.title}</h2>
                      
                    </div>
                  </div>
                )
              }
              else if(post.kind == 't1') {
                // This is for comments
                return (
                    <div className="wrapper fixed block" key={key}>
                      <div>
                        <ReactMarkdown>{betterwrap(post.data.body, 10, "<br/>", true)}</ReactMarkdown>
                      </div>
                    </div>
                  )
              }

              else {
                return (
                  <div className="wrapper fixed block" key={key}>
                    <div>
                      <h2 className={"block fixed " + styles.textcenter}>{post.data.title}</h2>
                      <p>{type}</p>
                    </div>
                  </div>
                )
              }
            })
          }

        </div>
      </main>
      </>
    )
}