import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import ModalVideo from 'react-modal-video'

export async function getServerSideProps() {
  try {
    const res = await fetch("https://www.reddit.com/r/memes.json");
    const posts = await res.json();
    return {
      props: {
        posts: posts.data.children,
        history: { memes: posts.data.after },
      }, // will be passed to the page component as props
    };
  } catch (error) {
    const err = error;
    return {
      props: {
        posts: [],
        err: JSON.stringify(err),
      }, // will be passed to the page component as props
    };
  }
}

export default function Home(props) {
  var posts = props['posts']

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/blocks.css/dist/blocks.min.css" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          
          {
          Object.entries(posts).map(([key, post]) => {
            let type = post.data.post_hint;
            if (type == "image"){
              return(
              <div className="wrapper fixed block" key={key}>
                  <div>
                    <h1 className="block fixed">{post.data.title}</h1>
                    <Image src={ post.data.url } height="300" />
                  </div>
                </div>
                )
            }
            else if (type == "link") {
              return(
                <div className="wrapper fixed block" key={key}>
                  <div>
                    <h1 className="block fixed">Link</h1>
                    <a href={post.data.url}>{post.data.title}</a>
                  </div>
                </div>
              )
            }
            else if (type == "hosted:video") {
              console.log()
              return(
                <div className="wrapper fixed block" key={key}>
                  <div>
                    <h1 className="block fixed">{post.data.title}</h1>


                  </div>
                </div>
              )
            }
            else {
              return(
                <div className="wrapper fixed block" key={key}>
                  <div>
                    <h1 className="block fixed">{post.data.title}</h1>
                    <p>{type}</p>
                  </div>
                </div>
              )
            }
          })
          }

        </div>
      </main>
    </div>
  )
}
